name: Release

on:
    push:
        branches:
            - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
    release:
        name: Release
        # prevents this action from running on forks
        if: github.repository == 'nodge/swc-plugin-barrel-files'
        permissions:
            contents: write # to create release
            issues: write # to post issue comments
            pull-requests: write # to create pull request
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Setup Rust
              uses: dtolnay/rust-toolchain@stable
              with:
                  targets: wasm32-wasip1

            - name: Cache Rust dependencies
              uses: Swatinem/rust-cache@v2

            - name: Install pnpm
              uses: pnpm/action-setup@v2
              with:
                  version: 9
                  run_install: false

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "22"
                  cache: "pnpm"
                  registry-url: "https://registry.npmjs.org"

            - name: Install dependencies
              run: pnpm install

            - name: Create Release PR or Publish to npm
              id: changesets
              uses: changesets/action@v1
              with:
                  title: "Upcoming Release"
                  commit: "chore(release): version bump"
                  publish: pnpm ci:release
                  version: pnpm ci:version
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
